---
- name: playbook for Tomcat installation
  hosts: all
  become: true
  become_user: root
  vars:
    tomcat_url: "https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.67/bin/apache-tomcat-9.0.67.tar.gz"
    tomcat_package: "apache-tomcat-9.0.67"
    
  tasks:
  - name: Install Java
    apt:
      name: openjdk-11-jdk
      state: latest
   
  - name: Install Tomcat from apache tomcat website
    get_url: 
      url: "{{ tomcat_url }}"
      dest: /usr/local
      
  - name: Unarchive tomcat package
    unarchive:
      src: /usr/local/{{ tomcat_package }}.tar.gz
      dest: /usr/local
      remote_src: yes
