---
- name: Playbook for Tomcat Ansible deploy
  hosts: all
  become: true
  become_user: root
 
  tasks:
  - name: Starting tomcat server
    shell: nohup /usr/local/apache-tomcat-9.0.65/bin/startup.sh &
    become: true
  

  - name: Copying the war file to tomcat server location
    copy:
      src: /home/bd/agent-1/workspace/Spring-Boot-Thymeleaf/target/spring-boot-thymeleaf-2.0.0.war 
      dest: /usr/local/apache-tomcat-9.0.65/webapps
      
  - name: Starting tomcat server
    shell: nohup /usr/local/apache-tomcat-9.0.65/bin/startup.sh &
    become: true
