# Playbook for deleting the existing package and deploying the fresh build

---
- name: Playbook for Tomcat Ansible deploy
  hosts: all
  become: true
  become_user: root
  #vars:
  #  tomcat_package: "apache-tomcat-9.0.67"
  #vars_files:
  #- variables.yml
 
  tasks:
  - include_vars: variables.yml
  
  - name: Checking if the package is present
    stat:
      path: /usr/local/{{ tomcat_package }}/webapps/{{ war_package }}
    register: result
  
  - name: Deleting the build if it exists
    file:
      path: /usr/local/{{ tomcat_package }}/webapps/{{ war_package }}
      state: absent
    when: result.stat.exists
    
  - name: Copying the war file to tomcat server location
    copy:
      src: /home/bd/agent-1/workspace/Spring-Boot-Thymeleaf/target/{{ war_package }}
      dest: /usr/local/{{ tomcat_package }}/webapps
      
  - name: Restarting tomcat server
    shell: 
      cmd: nohup /usr/local/{{ tomcat_package }}/bin/shutdown.sh & nohup /usr/local/{{ tomcat_package }}/bin/startup.sh
