apiVersion: apps/v1
kind: Deployment
metadata:
     name: myapp-deployment
     labels:
         app: myapp-deploy

spec:
     replicas: 2
     selector:
         matchLabels:
                app: myapp-spring-boot
     template:
         metadata:
                labels:
                    app: myapp-spring-boot
         spec:
                containers: 
                 -  name: myapp-container
                    image: bharadwajayinapurapu/spring-boot-thymeleaf:tagVersion
                    ports: 
                     -  containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
     name: myapp-service
     labels:
         app: myapp

spec:
     loadBalancerIP: 20.207.84.96
     selector:
         app: myapp-spring-boot
     type: LoadBalancer
     ports:
      -  port: 80
         targetPort: 8080
