- name: Install Java
  apt:
      name: openjdk-11-jdk
      state: latest
  
- name: Install Tomcat
  get_url:
      url: https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.67/bin/apache-tomcat-9.0.67.tar.gz
      dest: /usr/local

- name: Unarchive Tomcat Package
  unarchive:
      src: /usr/local/apache-tomcat-9.0.67.tar.gz
      dest: /usr/local
      remote_src: yes
